FROM alpine

RUN mkdir -p /files

RUN echo "Hello, World 1! \$(date)" > /files/001.txt
RUN echo "Hello, World 2! \$(date)" > /files/002.txt
RUN echo "Hello, World 3! \$(date)" > /files/003.txt
RUN echo "Hello, World 4! \$(date)" > /files/x/004.txt
RUN echo "Hello, World 4! \$(date)" > /files/x/005.txt
RUN echo "Hello, World 5! \$(date)" > /files/y/006.txt
