name: "Build Action (if not available)"

on: [workflow_call]

jobs:
  build-action:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/heads/release')"
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Build action (if not already built)
        run: npm run build
      - name: Push build into cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ github.sha }}
