name: Test Directory Extraction

on: [push]

jobs:
  extract-directory:
    runs-on: ubuntu-latest
    name: Extract Contents of Directory from Example Image
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files
      - run: test -e ${{ steps.extract.outputs.destination }}/001.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/002.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/003.txt || exit 1
