name: Test Directory Extraction

on: [push, pull_request]

jobs:
  action:
    uses: ./.github/workflows/build_action.yaml
  root-directory:
    runs-on: ubuntu-latest
    needs:
      - action
    name: Extract Contents of Directory from Example Image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Load action build from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ github.sha }}
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files/.
      - run: test -e ${{ steps.extract.outputs.destination }}/001.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/002.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/003.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/x/004.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/x/005.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/y/006.txt || exit 1
  nested-directory:
    runs-on: ubuntu-latest
    needs:
      - action
    name: Extract Nested Directory from Example Image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Load action build from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ github.sha }}
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files/x
      - run: test -e ${{ steps.extract.outputs.destination }}/x/004.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/x/005.txt || exit 1
  nested-directory-contents:
    runs-on: ubuntu-latest
    needs:
      - action
    name: Extract Nested Contents of Directory from Example Image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Load action build from cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ github.sha }}
      - run: docker build -t example:${{ github.sha }} ./.github/tests
      - uses: ./
        id: extract
        with:
          image: example:${{ github.sha }}
          path: /files/x/.
      - run: test -e ${{ steps.extract.outputs.destination }}/004.txt || exit 1
      - run: test -e ${{ steps.extract.outputs.destination }}/005.txt || exit 1
